2021-09-17 11:01:00,342 INFO    MainThread:203244 [wandb_setup.py:_flush():69] setting env: {}
2021-09-17 11:01:00,342 INFO    MainThread:203244 [wandb_setup.py:_flush():69] setting login settings: {}
2021-09-17 11:01:00,342 INFO    MainThread:203244 [wandb_init.py:_log_setup():342] Logging user logs to /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/NLP/Consumer-Complaints-NLP/wandb/run-20210917_110100-cheufsvc/logs/debug.log
2021-09-17 11:01:00,342 INFO    MainThread:203244 [wandb_init.py:_log_setup():343] Logging internal logs to /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/NLP/Consumer-Complaints-NLP/wandb/run-20210917_110100-cheufsvc/logs/debug-internal.log
2021-09-17 11:01:00,343 INFO    MainThread:203244 [wandb_init.py:init():375] calling init triggers
2021-09-17 11:01:00,343 INFO    MainThread:203244 [wandb_init.py:init():382] wandb.init called with sweep_config: {}
config: {}
2021-09-17 11:01:00,343 INFO    MainThread:203244 [wandb_init.py:init():397] re-initializing run, found existing run on stack: n2ckqjn0
2021-09-17 11:01:00,344 INFO    MainThread:203244 [wandb_run.py:finish():1271] finishing run ranuga-d/Consumer-Complaints-NLP/n2ckqjn0
2021-09-17 11:01:00,357 INFO    MainThread:203244 [jupyter.py:save_history():382] saving 44 cells to _session_history.ipynb
2021-09-17 11:01:00,370 INFO    MainThread:203244 [wandb_run.py:_config_callback():843] config_cb ('_wandb', 'session_history') code/_session_history.ipynb None
2021-09-17 11:01:00,399 INFO    MainThread:203244 [jupyter.py:save_ipynb():301] looking for notebook: 00.ipynb
2021-09-17 11:01:00,975 INFO    MainThread:203244 [wandb_init.py:_jupyter_teardown():274] saved code and history
2021-09-17 11:01:00,976 INFO    MainThread:203244 [wandb_init.py:_jupyter_teardown():275] cleaning up jupyter logic
2021-09-17 11:01:00,976 INFO    MainThread:203244 [wandb_run.py:_atexit_cleanup():1571] got exitcode: 0
2021-09-17 11:01:00,976 INFO    MainThread:203244 [wandb_run.py:_restore():1543] restore
2021-09-17 11:01:02,436 INFO    MainThread:203244 [wandb_init.py:init():424] starting backend
2021-09-17 11:01:02,436 INFO    MainThread:203244 [backend.py:_multiprocessing_setup():72] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-09-17 11:01:02,439 INFO    MainThread:203244 [backend.py:ensure_launched():135] starting backend process...
2021-09-17 11:01:02,486 INFO    MainThread:203244 [backend.py:ensure_launched():140] started backend process with pid: 206610
2021-09-17 11:01:02,487 INFO    MainThread:203244 [wandb_init.py:init():429] backend started and connected
2021-09-17 11:01:02,498 INFO    MainThread:203244 [wandb_run.py:_label_probe_notebook():815] probe notebook
2021-09-17 11:01:02,499 INFO    MainThread:203244 [wandb_init.py:init():477] updated telemetry
2021-09-17 11:01:02,500 INFO    MainThread:203244 [wandb_init.py:init():500] communicating current version
2021-09-17 11:01:03,398 INFO    MainThread:203244 [wandb_init.py:init():505] got version response upgrade_message: "wandb version 0.12.2 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-09-17 11:01:03,399 INFO    MainThread:203244 [wandb_init.py:init():513] communicating run to backend with 30 second timeout
2021-09-17 11:01:03,872 INFO    MainThread:203244 [wandb_init.py:init():540] starting run threads in backend
